// <auto-generated />
using ContactManager.BL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.BL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContactManager.BL.Models.Contact", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailAddress");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            EmailAddress = "mn@nerdymail.com",
                            FirstName = "Michelle",
                            LastName = "Nesbitt"
                        },
                        new
                        {
                            EmailAddress = "men@nerdymail.com",
                            FirstName = "Michelle",
                            LastName = "Nesbitt"
                        });
                });

            modelBuilder.Entity("ContactManager.BL.Models.EmailAddresses", b =>
                {
                    b.Property<int>("EmailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailID"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailType")
                        .HasColumnType("int");

                    b.HasKey("EmailID");

                    b.ToTable("EmailAddresses");

                    b.HasData(
                        new
                        {
                            EmailID = 1,
                            EmailAddress = "mn@nerdymail.com",
                            EmailType = 1
                        },
                        new
                        {
                            EmailID = 2,
                            EmailAddress = "men@nerdymail.com",
                            EmailType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
